config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  resources :games do
    member do
      get :play
      post :set_piece
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# # app/models/game.rb
# class Game < ApplicationRecord
#   serialize :state, Array

  
# end

class Game < ApplicationRecord
  validates :state, presence: true
  validates :current_player, presence: true
  serialize :state, Array


  def initialize_board
    self.assign_attributes(state: Array.new(6) { Array.new(7) { 0 } }, current_player: 1)
    return self
  end

  def empty_row?(column)
    state.map { |r| r[column] }.reverse.index(0).present?
  end

  def get_empty_row(column)
    index = state.map { |r| r[column] }.reverse.index(0)
    return 5 - index unless index.nil?

    -1 # Column is full
  end

  def set_tile_and_player(row, column)

    self.state[row][column] = self.current_player
    tile_class = self.current_player == 1 ? "red-piece" : "yellow-piece"
    game_winner = check_winner(state).to_i
    self.winner = game_winner if game_winner > 0
    self.current_player = self.current_player == 1 ? 2 : 1
    save
    return tile_class
  end
  
  def check_winner(board)
    # Check for consecutive wins (1s or 2s)
    players = [1, 2]
    players.each do |player|
      # Check horizontal wins
      board.each do |row|
        consecutive_count = 0
        row.each do |cell|
          consecutive_count = (cell == player) ? consecutive_count + 1 : 0
          return player if consecutive_count >= 4
        end
      end
  
      # Check vertical wins
      (0...board.first.size).each do |col_index|
        consecutive_count = 0
        board.each do |row|
          cell = row[col_index]
          consecutive_count = (cell == player) ? consecutive_count + 1 : 0
          return player if consecutive_count >= 4
        end
      end
  
      # Check diagonal wins (downward)
      (0...board.size - 3).each do |row_index|
        (0...board.first.size - 3).each do |col_index|
          consecutive_count = 0
          (0..3).each do |offset|
            next if row_index + offset >= board.size || col_index + offset >= board.first.size
            consecutive_count = (board[row_index + offset][col_index + offset] == player) ? consecutive_count + 1 : 0
            return player if consecutive_count >= 4
          end
        end
      end
  
      # Check diagonal wins (upward)
      (3...board.size).each do |row_index|
        (0...board.first.size - 3).each do |col_index|
          consecutive_count = 0
          (0..3).each do |offset|
            next if row_index - offset < 0 || col_index + offset >= board.first.size
            consecutive_count = (board[row_index - offset][col_index + offset] == player) ? consecutive_count + 1 : 0
            return player if consecutive_count >= 4
          end
        end
      end
    end
  
    # No winner found
    return nil
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
# app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show update set_piece destroy]

  
  def play
    @game = Game.find(params[:id])
  end
  def index
    @games = Game.all
  end


  def create
    @game = Game.new.initialize_board
    if @game.save
      redirect_to play_game_path(@game)
    else
      render json: @game.errors, status: :unprocessable_entity
    end
  end

  def set_piece
    return if @game_over
    column = params['coords'].split("-")[1].to_i
    row = @game.get_empty_row(column)
    return if row == -1 # Column is full

    tile_class = @game.set_tile_and_player(row, column)

    render json: { status: 200, id: "#{row}-#{column}", class: tile_class, winner: @game.winner}
  end

  def destroy
    @game.destroy
    respond_to do |format|
      if @game.destroyed?
        format.html { redirect_to games_path, notice: "Game deleted successfully!" }
        format.json { head :no_content }
      else
        format.html { redirect_to games_path, alert: "Failed to delete game!" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
    @game_over = false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<br>

<%= link_to 'New Game', new_game_path %>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Current player</th>
      <th>Winner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.id %></td>
        <td><%= game.current_player %></td>
        <td><%= game.winner %></td>
        <td><%= link_to 'Show / Edit', play_game_path(game) %></td>
        <td><%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<!-- app/views/games/new.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Connect Four</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <h1>Connect Four</h1>
    <%= link_to 'Play Game', games_path, method: :post %>

</body>
</html>

app/views/games/play.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Connect 4</title>

</head>
<body>
    <h1>Connect 4</h1>
    <% if @game.winner.present? %>
    <h2 id="winner">Player <%= @game.winner %> is the winner</h2>
  <% else %>
    <h2 id="winner"></h2>
  <% end %>
  
    <div id="board">
    <% @game.state.each_with_index do |row, r| %>
        <% row.each_with_index do |cell, c| %>
            <div id="<%= "#{r}-#{c}" %>" class=" tile <%= cell == 0 ? 'empty' : (cell == 1 ? 'red-piece' : 'yellow-piece') %> <%= @game.winner != nil ? 'disabled-click' : '' %>" onclick="callSetPiece(<%= @game.id %>, event)"></div>
        <% end %>
      <% end %>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConnectFourApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="games.css">
    <link rel="script" href="games.js">
  </head>

  <body>
    <%= yield %>
  </body>
</html>